baseURL = 'https://user0608.github.io/pruebita-hugo/'
languageCode = 'en-us'
title = 'Callo Blog'
theme = "soho"

[menu]
    [[menu.main]]
    name="Posts"
    identifer= "posts"
    weight =100 
    url="/posts"


[[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "/googoogogo"

   [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://www.github.com/user0608"

